
## <font color='red'> FUNCTIONS, FILTERS AND LAMBDA EXPRESSIONS  </font> 

# <font color='blue'> 1. WRITE A FUNCTION THAT TAKES A VARIABLE AND SQUARE IT, THEN TEST THE FUNCTION BY TAKING AN INPUT FROM A USER

In [21]:
def square(x):
    return x ** 2
num = input("Enter a number: ")
num = float(num)
result = square(num)
print("The square of", num, "is", result) 

Enter a number: 67.9
The square of 67.9 is 4610.410000000001


# <font color='blue'> 2. WRITE A FUNCTION THAT TAKES 2 VARIABLE AND OBTAIN THE SUMMATION AND MULTIPLICATION, THEN TEST THE FUNCTION BY TAKING AN INPUT FROM A USER (REPEAT USING LAMBDA EXPRESSIONS)

# LAMBDA

In [32]:
def sum_mul(x, y):

    return x + y, x * y

num1 = input("Enter first number: ")
num2 = input("Enter second numbers: ")

num1 = float(num1)
num2 = float(num2)

sum_result, mul_result = sum_mul(num1, num2)
print("The sum of", num1, "and", num2, "is", sum_result)
print("The multiplication of", num1, "and", num2, "is", mul_result)


Enter first number: 5
Enter second numbers: 6
The sum of 5.0 and 6.0 is 11.0
The multiplication of 5.0 and 6.0 is 30.0


In [33]:
def sum_mul(x, y):

    return 
num1 = input("Enter first number: ")
num2 = input("Enter second numbers: ")
num1 = float(num1)
num2 = float(num2)

sum_mul_lambda = lambda x, y: (x + y, x * y)

sum_result_lambda, mul_result_lambda = sum_mul_lambda(num1, num2)
print("The sum of", num1, "and", num2, "using lambda is", sum_result_lambda)
print("The multiplication of", num1, "and", num2, "using lambda is", mul_result_lambda)


Enter first number: 5
Enter second numbers: 6
The sum of 5.0 and 6.0 using lambda is 11.0
The multiplication of 5.0 and 6.0 using lambda is 30.0


#  <font color='blue'>3. WRITE A FUNCTION THAT TAKES A VARIABLE AND RETURNS ITS FACTORIAL </font> 

In [57]:
def factorial(n):
    
    if n == 0:
        return 1
    elif n < 0:
        print("Invalid value. Please enter a positive integer.")
    else:
        result = 1
        for i in range(1, n + 1):
            result *= i
        return result
num = input("Enter a positive integer: ")
num = int(num)
result = factorial(num)
print(result)


Enter a positive integer: 7
5040


# <font color='blue'> 4. DEVELOP A SCRIPT WHOSE ITEMS ARE SQUARES OF THE ORIGINAL LIST </font> 

In [43]:
original_list = [1, 2, 3, 4, 5]

squared_list = [x ** 2 for x in original_list]

print("Original List:", original_list)
print("Squared List:", squared_list)


Original List: [1, 2, 3, 4, 5]
Squared List: [1, 4, 9, 16, 25]


# <font color='blue'> 5. WRITE A FUNCTION THAT SQUARES A VARIABLE AND THEN TEST THE FUNCTION USING A LIST OF INTEGER NUMBERS RANGING FROM -20 to 20

In [64]:
def square(x):
    return x ** 2
num = input("Enter a number: ")
num = int(num)
result = square(num)
print("The square of", num, "is", result) 

Enter a number: 3
The square of 3 is 9


In [61]:
#Test the function
List = list(range(-20, 21))
num=int(num)
for num in List:
    result = number(num)
    print("The square of", num, "is", result)

The square of -20 is 400
The square of -19 is 361
The square of -18 is 324
The square of -17 is 289
The square of -16 is 256
The square of -15 is 225
The square of -14 is 196
The square of -13 is 169
The square of -12 is 144
The square of -11 is 121
The square of -10 is 100
The square of -9 is 81
The square of -8 is 64
The square of -7 is 49
The square of -6 is 36
The square of -5 is 25
The square of -4 is 16
The square of -3 is 9
The square of -2 is 4
The square of -1 is 1
The square of 0 is 0
The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
The square of 5 is 25
The square of 6 is 36
The square of 7 is 49
The square of 8 is 64
The square of 9 is 81
The square of 10 is 100
The square of 11 is 121
The square of 12 is 144
The square of 13 is 169
The square of 14 is 196
The square of 15 is 225
The square of 16 is 256
The square of 17 is 289
The square of 18 is 324
The square of 19 is 361
The square of 20 is 400


# <font color='blue'> 6. WRITE 3 FUNCTIONS THAT TAKE THE RADIUS OF A CIRCLE AND RETURN THE DIAMETER, AREA AND CIRCUMFERENCE, TEST THE FUNCTION USING AN INPUT FROM A USER 

In [67]:
pi = 22 / 7
def diameter(r):
    return 2 * r
def area(r):
    return pi * r ** 2
def circumference(r):
    return 2 * pi * r
r = input("Enter a radius: ")
r = float(r)
print("The diameter of a circle with radius", r, "is", diameter(r))
print("The area of a circle with radius", r, "is", area(r))
print("The circumference of a circle with radius", r, "is", circumference(r))

Enter a radius: 8
The diameter of a circle with radius 8.0 is 16.0
The area of a circle with radius 8.0 is 201.14285714285714
The circumference of a circle with radius 8.0 is 50.285714285714285


# <font color='blue'> 7. WRITE A CODE THAT TAKES A RANGE FROM A USER (UPPER AND LOWER BOUND) AND RETURNS A LIST OF POSITIVE AND EVEN NUMBERS ONLY

In [4]:
lower, upper = input("Enter the lower and upper bounds of the range, separated by a space: ").split()

upper = int(upper)
lower = int(lower)
my_range = range(lower, upper + 1, 1)

my_list = [number for number in my_range if number > 0 and number % 2 == 0]

print(my_list)


Enter the lower and upper bounds of the range, separated by a space: 50 500
[50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420, 422, 424, 426, 428

# <font color='blue'> 8. USING FILTER AND LAMBDA EXPRESSION, WRITE A CODE THAT TAKES A LIST OF NUMBERS BELOW AND RETURNS EVEN NUMBERS ONLY

In [7]:
lambda x: x % 2 == 0
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_list = filter(lambda x: x % 2 == 0, my_list) 
even_list = list(even_list) 
print(even_list) 


[2, 4, 6, 8, 10]


# <font color='blue'> 9. WRITE A FUNCTION THAT TAKES TWO NUMPY MATRICES AND RETURN THE ADDITION, SUBTRACTION, TRANSPOSE, PRODUCT, DOT PRODUCT

In [10]:
import numpy as np 
matrix1 = np.array([[1, 2], [3, 4]])
print(matrix1)

def matrix_operations(matrix1, matrix2):
    if np.shape(matrix1) == np.shape(matrix2):
        addition = matrix1 + matrix2
        subtraction = matrix1 - matrix2
        transpose1 = matrix1.T
        transpose2 = matrix2.T
        product = matrix1 * matrix2
        dot_product = matrix1 @ matrix2

    else:
        print("The matrices do not have the same shape.")
    return addition, subtraction, transpose1, transpose2, product, dot_product

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

addition, subtraction, transpose1, transpose2, product, dot_product = matrix_operations(matrix1, matrix2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Transpose of matrix1:\n", transpose1)
print("Transpose of matrix2:\n", transpose2)
print("Product:\n", product)
print("Dot product:\n", dot_product)


[[1 2]
 [3 4]]
Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Transpose of matrix1:
 [[1 3]
 [2 4]]
Transpose of matrix2:
 [[5 7]
 [6 8]]
Product:
 [[ 5 12]
 [21 32]]
Dot product:
 [[19 22]
 [43 50]]


# <font color='blue'> 10. WRITE A FUNCTION THAT TAKES TWO VALUES FROM A USER AND SUM THEM UP. IF NO VALUES ARE PROVIDED, ASSUME DEFAULT VALUES OF 3 AND 5

In [14]:
def add(x=3, y=5):
    return x + y

try:
    user_input = input("Enter two numbers separated by a space: ")
    user_input = user_input.split()
    x, y = map(float, user_input)
    result = add(x, y)
    print("The sum of", x, "and", y, "is", result)
except:
    print("Invalid input. Using default values instead.")
    result = add()
    print("The sum of 3 and 5 is", result)


Enter two numbers separated by a space: 3 4
The sum of 3.0 and 4.0 is 7.0


# <font color='blue'> 11. WRITE A SCRIPT THAT WILL PROMPT A USER FOR A RANGE (MIN/MAX VALUE) AND RETURNS NUMBERS THAT ARE DIVISIBLE BY 4 BUT ARE NOT MULTIPLES OF 3 

In [23]:
min_value, max_value = input("Enter the minimum and maximum values of the range, separated by a space: ").split()

min_value = int(min_value)
max_value = int(max_value)

my_range = range(min_value, max_value + 1, 1)

my_list = [number for number in my_range if number % 4 == 0 and number % 3 != 0]

print(my_list)


Enter the minimum and maximum values of the range, separated by a space: 3 50
[4, 8, 16, 20, 28, 32, 40, 44]


# <font color='blue'> 12. DEFINE AN ENGLISH TO FRENCH TRANSLATOR FUNCTION THAT TAKES AN INPUT FROM A USER AND RETURNS THE TRANSLATION, USE ANY 5 KNOWN WORDS

In [28]:
def english_to_french_translator(word):
    translation_dict = {
        "hello": "bonjour",
        "cat": "chat",
        "dog": "chien",
        "house": "maison",
        "car": "voiture"
    }
    word = word.lower()
    if word in translation_dict:
        return translation_dict[word]
    else:
        return "Translation not found"
user_input = input("Enter an English word: ")
translation = english_to_french_translator(user_input)
print(f"The translation of '{user_input}' in French is '{translation}'.")


Enter an English word: dog
The translation of 'dog' in French is 'chien'.
